# install.packages("XLConnect")
# install.packages("genepop")
getwd()
library(genepop)
library(XLConnect)
# remotes::install_github("douglasgscofield/readGenalex")
library(readGenalex)
setwd("C:/Users/RIZWAN/Downloads/")
list.files()
gt<-readGenalexExcel("seema.xlsx",worksheet = 2)
writeGenepop(gt,"genepop.txt",check.annotation =FALSE)
genepop::basic_info("genepop.txt")
